# Generated by Django 4.1.6 on 2023-02-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('image', models.URLField(null=True)),
                ('heath', models.URLField(null=True)),
                ('url', models.URLField(null=True)),
                ('type', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('json', models.CharField(max_length=255)),
            ],
        ),
    ]
